name: Real App

on:
  push:
    branches: [ main ]
    tags:
      - 'v*'  # Trigger on version tags
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs: 
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    env:
      CI: false  # This will prevent treating warnings as errors

    steps:
      - uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Build React app
        run: cd src && npm install && npm run build && cd ..

      - name: Package Electron app
        if: matrix.os != 'macos-latest'
        run: npm run package

      - name: Package and Sign Electron app (macOS)
        if: matrix.os == 'macos-latest'
        run: |
          npm run package
          # Ad-hoc sign the app
          codesign --force --deep --sign - "dist/mac-arm64/REAL.app"

      - name: Upload dist folder
        uses: actions/upload-artifact@v4
        with:
          name: dist-${{ matrix.os }}
          path: dist/

  release:
    needs: build
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest
    steps:
      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            artifacts/dist-ubuntu-latest/**/*
            artifacts/dist-windows-latest/**/*
            artifacts/dist-macos-latest/**/*
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
